### ISSUE TITLE
Include Sphinx documentation

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#135]
Details here: https://github.com/amath-idm/covasim/pull/306

**Comment by JSchripsema-IDM** [comment]
Can someone merge my PR? I'm going to submit another change (addition of contributing doc), but it depends on those changes so I'm just going to add it to that PR. I can't get the HTML set up for hosting (which involves other changes needing to be made by our web dev in India) until the source changes are approved.

**Comment by ckerr-IDM** [comment]
@JSchripsema-IDM unfortunately i think there's likely to be a massive merge conflict...let me create it and see

**Comment by ckerr-IDM** [comment]
@JSchripsema-IDM I closed that PR and opened another one, are you able to resolve the merge conflicts here?
https://github.com/amath-idm/covasim/pull/337

Also, I see that
```
Example:
    a = 4
```
has been changed to:
```
**Example**
        ::
    a = 4
```
Could we restore the former formatting? I think it's a little closer to the official Google docstring format (https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html). Also, it looks like there are some other places where indentation in the docstrings may have gotten changed.

**Comment by JSchripsema-IDM** [comment]
Sphinx is very particular about indentation and I updated the docstrings where they were causing build errors. Similarly, the example heading was not formatted as such and the code was displayed in plain text as a single line in the build.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by ckerr-IDM** [comment]
@JSchripsema-IDM ah ok, that's annoying! so it understands `Args:` and `Returns:` but not `Examples:`?

**Comment by JSchripsema-IDM** [comment]
Yeah, it's weird. I'm not sure why the Examples heading isn't treated the same as the others, because you're right that it is closer to Google style.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by ckerr-IDM** [comment]
@JSchripsema-IDM Are you using Napoleon? Seeing as the 'Example' thing came from their website, I'd hope it was supported :) 
https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

**Comment by JSchripsema-IDM** [comment]
Yep, we’re using napoleon. I played around with it a bit and it’s because the Example(s) heading is immediately followed by a code sample that needs to be parsed as a code. It will format correctly when it’s followed by plain text. I tried the following other options and it isn’t compiled correctly with either:

Example:

::

              Code sample

Example:

.. code-block::

              Code sample

The only other option I can think of is to include a plain text intro to every code example, but that seems like more clutter than the syntax I added.

So did my updates to the contributing doc get included when you moved everything over to the other repo? I need to take some time off this evening after a couple long nights, but I can try and sort it out tomorrow.

**Comment by ckerr-IDM** [comment]
OK...ugh, what a nuisance. All updates should be included since the PR is still from your branch. @RomeshA you probably don't have anything to add here since you don't use Google docstrings, but checking just in case? And yes thank you, tomorrow is fine, thanks for all your work on this!

**Comment by ckerr-IDM** [comment]
Merged!
