### ISSUE TITLE
Put diagnosed people in quarantine?

### ISSUE THREAD

**Issue by cliffckerr** [InstituteforDiseaseModeling/covasim#208]
(From Kyle Gustafson) Currently, only contacts of a diagnosed person are counted as being in quarantine. Should the diagnosed person themselves also be counted in quarantine?

**Comment by kgustafs** [comment]
From my perspective - contact_tracing and test_prob (for example) are separate (and apparently uncoupled?) interventions but both could/should lead to quarantine of positive tests. 

Does the diagnosed person become removed from circulation in some other way than being counted in quarantine? I suppose they go to the "diagnosed" bin rather than the "infectious" bin. In practice, a person could be diagnosed and told to stay home but reject the advice, and in any case, if they stay home, they are probably still exposing household members - but then they should be contacts who are quarantined.

**Comment by cliffckerr** [comment]
Currently, people who are diagnosed are isolated, not in quarantine. To treat isolated people as being in quarantine, simply set `iso_factor == quar_factor`.
