### ISSUE TITLE
Model Parameters Tab: Probability Multipliers are misleading, should let people alter the actual multiplier and not a multiplier of multiplier. 

### ISSUE THREAD

**Issue by Sv3tlana** [InstituteforDiseaseModeling/covasim#221]
Covasim, webapp, expand the Model Parameters Tab.

When looking at the parameters, all of them are the actual parameters and let you edit the actual parameters that are used: Time to Infectiousness, Infection duration, etc.   
Then when you get to probability multipliers and they are actually multipliers of the secret probabilities that we use and we aren't telling you directly what they are. It's not very helpful to have a multiplier for a parameter that you don't know what it is. People would have to look at the graphs and guess what the parameters are or go look at our papers? on the front page?

I think it would make more sense instead of multipliers to have actual:
Symptomatic Probability, Severe Probability, Clinical Probability, and Death Probability. 
That way people can adjust them directly instead of multiplying a number that they don't know what it is. (I'm guessing it's somewhere in our papers or the parameter paper, but who wants to look for that on a whole another page)
![image](https://user-images.githubusercontent.com/16845361/80773774-bffcaf80-8b0f-11ea-9ba9-935dabf000bb.png)

**Comment by Sv3tlana** [comment]
The tooltip says "adjustment factor for literature-derived parameter". I think it would be clearer to just have that parameter there.

**Comment by cliffckerr** [comment]
@Sv3tlana That's the way it was before, but we changed it because the parameters are complex functions of age -- behind those probability multipliers are 36 other numbers (https://github.com/InstituteforDiseaseModeling/covasim/blob/master/covasim/parameters.py#L160) that we don't really want the users messing with -- even in our own analyses we don't touch them. I agree that for transparency it would be nice to have the actual value, but it's just too complex for a web interface. When the paper comes out people can read it there :)

**Comment by Sv3tlana** [comment]
Hm. I'm gonna think about how to make what you said into a tooltip. Maybe "multiplier for all the age-dependent probabilities of becoming symptomatic (paper to be released)" or something?

**Comment by SoccerGeekPhD** [comment]
One way to handle this would be to keep the multiplier in the UI, but show in a tooltip or second read-only widget the real values of those probabilities based on the current settings. IDK if that's possible.

**Comment by cliffckerr** [comment]
Closing for now since the UI needs a major overhaul
