### ISSUE TITLE
nowebapp not removing requirements correctly

### ISSUE THREAD

**Issue by jps1** [InstituteforDiseaseModeling/covasim#245]
[This checkin](https://github.com/InstituteforDiseaseModeling/covasim/commit/5c135c1cdbb40c99e8763eda56403d1644ed7d57#diff-2eeaed663bd0d25b7e608891384b7298) broke nowebapp functionality.  There was a reason it was using regex previously, and this simplified version doesn't correctly remove requirements that specify a version (e.g. scirisweb).

**Comment by cliffckerr** [comment]
@jps1 Ah good point -- I think the simplest (although not ideal) way of fixing this is just to change `scirisweb` to `scirisweb>=0.17.0` in the `nowebapp` list in `setup.py`. Do you want to make a PR for this?

**Comment by jps1** [comment]
Do you have something against the way it was done originally?  Relying on keeping the versions in sync between setup.py and requirements.txt seems error-prone.

**Comment by ckerr-IDM** [comment]
I see the argument, but I think maintainability wise it's easier to keep `webapp_reqs` be a strict subset of `requirements.txt` rather than having a non-obvious mapping between them (at least for the current situation where we literally just have a single pinned version that needs to be dealt with). The reason I changed it initially is that at some point the requirement was defined as `plotly-express` (pip is agnostic to hyphens/underscores), which the `\W` part of the regex fails on. Seeing as we're tracking one version of one package, which hasn't changed in over a month (and despite over 500 commits since then), I think it's OK to go with the most explicit solution, and avoid the extra import etc. For similar reasons, the Sciris and ScirisWeb versions are also hard-coded in https://github.com/InstituteforDiseaseModeling/covasim/blob/master/covasim/requirements.py. Yes, it would be possible to implement a programming solution to read these in from the `requirements.txt` file, along with some updates to the manifest file etc. to ensure it ends up in the right place after `pip install`, but to me at least, it feels easier to just change `0.17.0` to `0.17.1` in three places instead of one a few months from now. :)

**Comment by ckerr-IDM** [comment]
The "right" solution, as we've discussed, would be the ability to have a "negative" `extras_require`, so we could do `pip install covasim[nowebapp]`. But unfortunately that just doesn't seem possible with setuptools.

**Comment by cliffckerr** [comment]
Fixed in the current PR (not merged yet)
