### ISSUE TITLE
[CI] Create baseline with actions

### ISSUE THREAD

**Issue by inc0** [InstituteforDiseaseModeling/covasim#26]
Some tests will produce actual simulation results.

Every time PR is merged, we can run these and save results as json and generate plot. This can be commited to repo via actions. This will produce baseline that will allow us to compare PR runs against it and generate report to help reviewers

**Comment by cliffckerr** [comment]
Need to decide how to implement this in a maintainable way

**Comment by jules2689** [comment]
Is this the summary we would like to use?

**Comment by ckerr-IDM** [comment]
Yes thanks!

**Comment by jules2689** [comment]
I can't assign myself, but I'll look at this!

**Comment by jules2689** [comment]
@ckerr-IDM do you know if we will have a github token capable of committing to the repository in the `secrets`? I'd like one to automatically update the results on merge to master

**Comment by ckerr-IDM** [comment]
@jules2689 we could also just have it in the `tests` folder? would have some preference for it to be manual in case you want to do it other than on merging to master (especially since we have 2 repos), or if you want to skip a particular merge

**Comment by jules2689** [comment]
yea, a manual baseline could work!
In that case, this is _almost_ working here: https://github.com/jules2689/covasim/pull/10/

<img width="780" alt="image" src="https://user-images.githubusercontent.com/3074765/78517384-0702b980-778b-11ea-9ee1-48b01506fc46.png">


I have to clean this up and hopefully make it update itself, rather than always adding new comments.

😄
