### ISSUE TITLE
Using a different skestimator?

### ISSUE THREAD

**Issue by rbelew** [InstituteforDiseaseModeling/covasim#272]
if I specify `sim.compute_fit(skestimator='mutual_info_score')` I get back things like this mismatches dictionary:

```
#0: "cum_diagnoses": 19.992777912316274
#1: "cum_deaths":    16.984571415678
```
but if I compute mutual information myself, directly, from the `fit.pair` data,

```
diagMI = skmetric.adjusted_mutual_info_score(fit.pair['cum_diagnoses'][0],fit.pair['cum_diagnoses'][1])
deathMI = skmetric.adjusted_mutual_info_score(fit.pair['cum_deaths'][0],fit.pair['cum_deaths'][1])	
```

i get much different values:

diagMI = 0.1507339245541447
deathMI = 7.828137366591832e-13

why would that be?

**Expected behavior**

i would expect diagMI==fit.mismatches['cum_diagnoses'] and deathMI==fit.mismatches['cum_deaths'] 

**Platform**
 - Covasim version: Covasim 1.5.0 (2020-07-01)
 - OS: [e.g. Linux, Android] OSX 10.15

**Comment by cliffckerr** [comment]
Hi @rbelew , I think there are a couple things going on here. I get matching results with this code:
```
import covasim as cv
from sklearn import metrics as skmetric

sim = cv.Sim(datafile='/home/cliffk/idm/covasim/tests/example_data.csv')
sim.run()
sim.plot()

fit = sim.compute_fit(skestimator='adjusted_mutual_info_score', weights={'cum_diagnoses':1, 'cum_deaths':1})

print('Covasim:')
print(fit.mismatches)

diagMI = skmetric.adjusted_mutual_info_score(fit.pair['cum_diagnoses'][0],fit.pair['cum_diagnoses'][1])
deathMI = skmetric.adjusted_mutual_info_score(fit.pair['cum_deaths'][0],fit.pair['cum_deaths'][1])

print('sklearn:')
print('diag:', diagMI)
print('death:', deathMI)
```
using the default simulation and the data in `tests/example_data.csv`, which gives
```
Covasim:
#0: "cum_tests":     1.6219881031974273e-17
#1: "cum_diagnoses": 1.6219881031974273e-17
#2: "cum_deaths":    0.27289442985672063
sklearn:
diag: 1.6219881031974273e-17
death: 0.27289442985672036
```
So it looks like there are two things here:
1) Use of `mutual_info_score` vs `adjusted_mutual_info_score`
2) The default weights are deaths=10, diagnoses=5. The unweighted outputs are stored in `fit.gofs`, while the weighted ones are in `fit.mismatches`.

I'd also comment that MI is in the inverse of what's expected -- i.e. larger mismatch leads to _lower_ MI (as shown in this example where the MI for diagnoses is close to zero, because there are 0 diagnoses in the simulation and quite a few in the data). So to use MI, at least with a standard fitting procedure, would require taking the inverse, but it's not clear to me how divide-by-zero errors would be best avoided.

**Comment by rbelew** [comment]
Thanks again, Cliff, user error!  I missed my mutual_info_score vs **adjusted**_mutual_info_score substitution/typo, and had not appreciated the **unweighted** `fit.gofs` vs. **weighted** `fit.mismatches`.  Thanks for your patience.
