### ISSUE TITLE
Simulation should allow for modeling of Mask intervention effects

### ISSUE THREAD

**Issue by bguan** [InstituteforDiseaseModeling/covasim#286]
**Is your feature request related to a problem? Please describe.**

No.  To be effective as a tool for planning school reopening, this simulation should allow pervasiveness of masks as an additional input similar to distancing.  Some studies claim masks can reduce the risk of infection to the wearer by 65 percent, so schools that implement effective mask wearing can lesson the urgency of wide spread testing.

**Describe the solution you'd like**

Just like it allows for distancing effectiveness as a parameter to drive the simulation, it should allow an input for mask compliance as a percentage of population, and show the effect in the projection.

**Describe alternatives you've considered**

None.

**Additional context**

* Lancet, review of distancing, masks, and eye protection... (https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)31142-9/fulltext)

**Comment by cliffckerr** [comment]
Hi @bguan , thanks for your note. Masks are an important intervention and are already included in Covasim. You can use `cv.change_beta()` for this. We leave it up to the user to choose the parameters since there is so much uncertainty in both mask efficacy, as well as enormous variability in mask compliance. We've updated the documentation to make this clearer:
https://docs.idmod.org/projects/covasim/en/latest/covasim.interventions.html#covasim.interventions.change_beta
