### ISSUE TITLE
SYSTEM Requirements for covsim

### ISSUE THREAD

**Issue by furqan915** [InstituteforDiseaseModeling/covasim#307]
Hello,

I need to ask a very basic question. What are the basic requirements (RAM, Processor, etc) for running this innovative software for my analysis?. I have COVID-19 data comprised of daily deaths, daily cases etc. 

Thanks.

**Comment by rlatkows** [comment]
From my experience as a user of that software there are no special requirements for simple analyses.

RAM: Small size of simulations (like 1e3-1e4 agents) runs far below 250MB of RAM.
Realistic simulations of all individuals for a country of size 6mln - 40GB of RAM, 40mln - 250GB of RAM (includes covasim + additional data structures to read realistic data + several realistic connection layers).

Any CPU is capable to run covasim. We tested it on Intel i5/i7 “U” CPUs of 7th-9th generations and Power9 platforms. Using numba gives only around x2.5 speed improvement over disabling numba. We also haven’t observed any speed increase by enabling multithreading. 

So I would guess you can perhaps run it even on raspberry pi.

**Comment by cliffckerr** [comment]
Thanks for your question @furqan915 and for your comprehensive response @rlatkows ! That's correct, there are no specific requirements for running Covasim -- if you can run Python with Matplotlib you can run Covasim. If you do not have a very fast processor though, you might want to use a smaller population size (number of agents) so the simulations take less time to run however. You can scale up to the full population size using the `pop_scale` parameter. E.g., rather than running a simulation of 2 million agents, you could run with 200,000 agents with `pop_scale=10` and get nearly the same result, but 10x faster.

**Comment by cliffckerr** [comment]
Hi @furqan915  -- just letting you know that this question has been added to the FAQ in version 3.0.2.
