### ISSUE TITLE
covasim - local doc build failing (make html)

### ISSUE THREAD

**Issue by RCarter-IDM** [InstituteforDiseaseModeling/covasim#408]
(virt-covasim) C:\github\covasim\docs>make html
Running Sphinx v7.1.2
Covasim 3.1.4 (2022-10-22) — © 2020-2022 by IDM

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "c:\virt-covasim\lib\site-packages\sphinx\config.py", line 356, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "C:\github\covasim\docs\conf.py", line 19, in <module>
    import covasim as cv
  File "c:\github\covasim\covasim\__init__.py", line 18, in <module>
    from .defaults      import * # Depends on settings
  File "c:\github\covasim\covasim\defaults.py", line 10, in <module>
    import numba as nb
  File "c:\virt-covasim\lib\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "c:\virt-covasim\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "c:\virt-covasim\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

**Comment by RCarter-IDM** [comment]
steps to duplicate:

1) python -m venv virt-covasim (create virtual environment)
2) scripts\activate (activate virtual environment)
3) git clone https://github.com/RCarter-IDM/covasim.git (clone, after first creating fork)
4) pip install -e . (install from cloned repo, local)
5) pip install -r requirements.txt (from /docs dir)
6) make html (from /docs dir)

**Comment by cliffckerr** [comment]
@RCarter-IDM I wouldn't recommend using `venv` for this; `numba` doesn't seem to compile properly on it. I just tried these steps but using `conda create -n virt-covasim python -y; conda activate virt-covasim` instead of the first two steps, and the rest of the build worked fine. See also this PR that fixes some docs bugs:
https://github.com/amath-idm/covasim/pull/1427

**Comment by RCarter-IDM** [comment]
@cliffckerr, I get '404' with provided link: https://github.com/amath-idm/covasim/pull/1427. What's the difference between these two repos: https://github.com/amath-idm/covasim and https://github.com/InstituteforDiseaseModeling/covasim ?

**Comment by RCarter-IDM** [comment]
(NOTE: attached file has full error/output after running make html)
Results after using Anaconda for virtual environment:

Notebook error:
CellExecutionError in tutorials\tut_advanced.ipynb:

BrokenProcessPool


[makehtmloutput.txt](https://github.com/InstituteforDiseaseModeling/covasim/files/12401975/makehtmloutput.txt)

**Comment by cliffckerr** [comment]
Hm, that issue is probably related to multiprocessing on Windows (see e.g. [here](https://docs.idmod.org/projects/covasim/en/latest/faq.html#why-do-parallel-simulations-fail-on-windows-or-in-jupyter-notebooks)). But that problem should've been fixed by now.

Re: the two repos, amath-idm is our 'dev' repo and this is our 'public' repo (equivalent to `DtkTrunk` vs `EMOD`). Sorry for the delay, you should have access now.

**Comment by RCarter-IDM** [comment]
Closing, as this works fine with our RTD build and with Windows multiprocessing issue fixed.
